### ISSUE TITLE
`intstr.IntOrString` cannot be unmarshalled

### ISSUE THREAD

**Issue by enrichman** [kubewarden/k8s-objects-generator#34]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying the [namespace-label-propagator-policy](https://github.com/kubewarden/namespace-label-propagator-policy) I've encountered the following issue:

```
* admission webhook "clusterwide-epinio-namespace-propagator.kubewarden.admission" denied the request: internal server error: Guest call failure: json: cannot unmarshal number into Go struct field RollingUpdateDeployment.spec.strategy.rollingUpdate.maxUnavailable of type intstr.IntOrString
```

This can be easily replicated using the [k8s-objects](https://github.com/kubewarden/k8s-objects) and trying to unmarshal a `RollingUpdateDeployment`:

```go
func main() {
	ing := &appsv1.RollingUpdateDeployment{}
	err := json.Unmarshal([]byte(`{ "maxUnavailable": 5 }`), ing)
	fmt.Println("Error", err)
}
```
```
// Error json: cannot unmarshal number into Go struct field RollingUpdateDeployment.maxUnavailable of type intstr.IntOrString
```

Debugging a bit this is because of a wrong definition of the `IntOrString` object in the OpenAPI spec of Kubernetes:

```json
"io.k8s.apimachinery.pkg.util.intstr.IntOrString": {
    "description": "blabla",
    "format": "int-or-string",
    "type": "string"
}
```

This is a known issue (https://kubernetes.slack.com/archives/C0EG7JC6T/p1698148830188469) and it's tracked:
- https://github.com/kubernetes/kubernetes/issues/25716
- https://github.com/kubernetes/kubernetes/issues/79472

Also the ArgoCD project faced the same problem: https://github.com/argoproj/argo-events/pull/1466

Now the spec of the Kubernetes API is over the 3.0 and they are able to use the `anyOf` spec, but the `go-swagger` command is probably not going to work anyway, so I'm not sure if this should be handled in a different way.

### Expected Behavior

The `IntOrString` object should be unmarshalled in both of the case (int or string).

**Comment by enrichman** [comment]
@flavio thinking a bit about a possible fix. An easy workaround will be to provide a `patch.json` file, used to patch the original `swagger.json` Kubernetes file:

_patch.json_
```json
{
    "definitions": {
        "io.k8s.apimachinery.pkg.util.intstr.IntOrString": {
            "type": "object"
        }
    }
}
```

Then using `jq` you could apply this over the original `swagger.json` file

```bash
jq -s '.[0] * .[1]' swagger.json patch.json > swagger-patched.json
```

and then use the `swagger-patched.json` to generate the k8s-objects.

In this case the outcome of this will be a `jsonext.RawMessage` instead of a "wrong" type, leaving the user to handle the type manually in the policy, if they need to:

```go
// RollingUpdateDeployment Spec to control the desired behavior of rolling update.
//
// swagger:model RollingUpdateDeployment
type RollingUpdateDeployment struct {

	// The maximum number of pods that can be scheduled above the desired number of pods. Value can be an absolute number (ex: 5) or a percentage of desired pods (ex: 10%). This can not be 0 if MaxUnavailable is 0. Absolute number is calculated from percentage by rounding up. Defaults to 25%. Example: when this is set to 30%, the new ReplicaSet can be scaled up immediately when the rolling update starts, such that the total number of old and new pods do not exceed 130% of desired pods. Once old pods have been killed, new ReplicaSet can be scaled up further, ensuring that total number of pods running at any time during the update is at most 130% of desired pods.
	MaxSurge jsonext.RawMessage `json:"maxSurge,omitempty"`

	// The maximum number of pods that can be unavailable during the update. Value can be an absolute number (ex: 5) or a percentage of desired pods (ex: 10%). Absolute number is calculated from percentage by rounding down. This can not be 0 if MaxSurge is 0. Defaults to 25%. Example: when this is set to 30%, the old ReplicaSet can be scaled down to 70% of desired pods immediately when the rolling update starts. Once new pods are ready, old ReplicaSet can be scaled down further, followed by scaling up the new ReplicaSet, ensuring that the total number of pods available at all times during the update is at least 70% of desired pods.
	MaxUnavailable jsonext.RawMessage `json:"maxUnavailable,omitempty"`
}

```

I';m not sure if the user can unmarshal this into the corresponding IntOrString struct. This works, but I'm not sure about the wasm compilation:

```go
func main() {
	rollPerc := &appsv1.RollingUpdateDeployment{}
	_ = json.Unmarshal([]byte(`{ "maxUnavailable": "5%" }`), rollPerc)
	fmt.Println("Roll Perc:", rollPerc.MaxUnavailable)

	intOrStr := &intstr.IntOrString{}
	_ = json.Unmarshal(rollPerc.MaxUnavailable, intOrStr)
	fmt.Println(intOrStr.String())

	rollInt := &appsv1.RollingUpdateDeployment{}
	_ = json.Unmarshal([]byte(`{ "maxUnavailable": 5 }`), rollInt)
	fmt.Println("Roll Int:", rollInt.MaxUnavailable)

	intOrStr = &intstr.IntOrString{}
	_ = json.Unmarshal(rollInt.MaxUnavailable, intOrStr)
	fmt.Println(intOrStr.IntValue())
}
```

```
Roll Perc: [34 53 37 34]
5%
Roll Int: [53]
5
```

What do you think? Could this be a fix, until the generator will move and support the OpenAPI v3 spec (this task needs probably a separate issue)?

**Comment by flavio** [comment]
Sorry for not having followed up here, but I was already working on a fix.

We are going to have the same `IntOrString` the official Kubernetes SDK offers, in this way the serialize/deserialize works as expected. Accessing the internal value will work in the very same way as the upstream SDK.

I'm currently rebuilding the `k8s-objects` branches to include the fix.
