### ISSUE TITLE
Feature Request: Generate ObjectKind interface implementation for each openAPI resource

### ISSUE THREAD

**Issue by dmvolod** [kubewarden/k8s-objects-generator#4]
### Is your feature request related to a problem?

It would be nice to have a feature similar to vanilla Kubernetes API GVK for each resource, using hard-coded values instead of getting via reflection.
It will be useful to implement `go-client` or `controller-runtime` like approaches for running with TinyGo 

### Solution you'd like

For this case, we could probably generate additional  `<resource>_gvk.go` file for each resource, i.e. `core/v1/ConfigMap`, etc which implemented ObjectKind interface.

```go
// Code generated by GroupVersionResource generator for getting GVK data. DO NOT EDIT.

package v1

import "github.com/kubewarden/k8s-objects/apimachinery/pkg/runtime/schema"

func (v *ConfigMap) GroupVersionKind() schema.GroupVersionKind {
	kind := v.Kind
	apiVersion := v.APIVersion
	if kind == "" {
		kind = "ConfigMap"
	}
	if apiVersion == "" {
		apiVersion = SchemeGroupVersion.String()
	}

	return schema.FromAPIVersionAndKind(apiVersion, kind)
}
```

Also `pkg/runtime/schema/group_version.go` can be ported/copied to be able to run this approach with TinyGo and additional `runtime.Object` interface for casting objects in the clients when needed.

### Alternatives you've considered

Not sure, we could have alternative approach with additional Kubernetes API with TinyGo
Otherwise, it would be nice to have a fully-functional port of most of the apimachinery objects ported to TinyGo

**Comment by dmvolod** [comment]
@flavio , @jvanz could you please to have a look at this approach.
Will try to implement it if will be suitable. Thanks in advance.

**Comment by flavio** [comment]
I think this would be a nice addition. If you implement it I'll be happy to review the PR

**Comment by dmvolod** [comment]
Yes, working on it.
